# Generated by Django 5.2.5 on 2025-10-04 05:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Passkey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="User-defined label for this passkey (e.g., 'iPhone 15', 'YubiKey')",
                        max_length=255,
                    ),
                ),
                (
                    "credential_id",
                    models.TextField(help_text="WebAuthn credential ID (base64 encoded)", unique=True),
                ),
                (
                    "public_key",
                    models.TextField(help_text="Public key for credential verification (base64 encoded)"),
                ),
                (
                    "sign_count",
                    models.IntegerField(
                        default=0,
                        help_text="Signature counter for replay attack prevention",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the passkey was created",
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when the passkey was last used for authentication",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "passkey",
                "verbose_name_plural": "passkeys",
                "ordering": ["-created_at"],
            },
        ),
    ]
