# Generated by Django 5.2.5 on 2025-10-04 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("authentication", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="passkey",
            name="user",
            field=models.ForeignKey(
                help_text="User who owns this passkey",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="passkeys",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="passkey",
            index=models.Index(fields=["user", "-created_at"], name="authenticat_user_id_34a035_idx"),
        ),
        migrations.AddIndex(
            model_name="passkey",
            index=models.Index(fields=["credential_id"], name="authenticat_credent_02748c_idx"),
        ),
    ]
