# Generated by Django 5.2.9 on 2025-12-07 04:52

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Service type name (e.g., 'Oil Change')",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", help_text="Optional description"
                    ),
                ),
                (
                    "is_custom",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="False for system defaults",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(db_index=True, default=0),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this custom type (null for system defaults)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_service_types",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(help_text="Business name", max_length=255)),
                (
                    "address",
                    models.TextField(blank=True, default="", help_text="Full address"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, default="", help_text="Phone number", max_length=50
                    ),
                ),
                (
                    "google_place_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Google Places ID for 'open in maps' functionality",
                        max_length=255,
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(db_index=True, default=0),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shops",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Nickname for the vehicle (e.g., 'Daily Driver')",
                        max_length=100,
                    ),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        help_text="Model year (e.g., 2020)"
                    ),
                ),
                (
                    "make",
                    models.CharField(
                        help_text="Manufacturer (e.g., 'Toyota')", max_length=100
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        help_text="Model name (e.g., 'Camry')", max_length=100
                    ),
                ),
                (
                    "vin",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Vehicle Identification Number (optional)",
                        max_length=17,
                    ),
                ),
                (
                    "license_plate",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="License plate number",
                        max_length=20,
                    ),
                ),
                (
                    "engine",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Engine description (e.g., '2.5L 4-Cylinder')",
                        max_length=100,
                    ),
                ),
                (
                    "trim",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Trim level (e.g., 'SE', 'Limited')",
                        max_length=100,
                    ),
                ),
                (
                    "current_odometer",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Current odometer reading in miles",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "odometer_updated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the odometer was last updated",
                        null=True,
                    ),
                ),
                (
                    "photo_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="URL to vehicle photo (stored in Garage S3)",
                        max_length=500,
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Archived vehicles are hidden but not deleted",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(db_index=True, default=0),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ServiceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("date", models.DateField(db_index=True, help_text="Date of service")),
                (
                    "odometer",
                    models.PositiveIntegerField(
                        help_text="Odometer reading at time of service",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "parts_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Cost of parts",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "labor_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Cost of labor (typically 0 for DIY)",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Additional notes about the service",
                    ),
                ),
                (
                    "service_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_records",
                        to="vehicle_maintenance_tracker.servicetype",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        blank=True,
                        help_text="Service location (null for DIY)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="service_records",
                        to="vehicle_maintenance_tracker.shop",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_records",
                        to="vehicle_maintenance_tracker.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Reminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "mileage_interval",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Miles between services (e.g., 5000)",
                        null=True,
                    ),
                ),
                (
                    "time_interval_months",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Months between services (e.g., 6)",
                        null=True,
                    ),
                ),
                (
                    "last_completed_date",
                    models.DateField(
                        blank=True,
                        help_text="Date of last completed service",
                        null=True,
                    ),
                ),
                (
                    "last_completed_odometer",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Odometer at last completed service",
                        null=True,
                    ),
                ),
                (
                    "next_due_date",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        help_text="Calculated next due date",
                        null=True,
                    ),
                ),
                (
                    "next_due_odometer",
                    models.PositiveIntegerField(
                        blank=True, help_text="Calculated next due odometer", null=True
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "is_manufacturer_recommended",
                    models.BooleanField(
                        default=False,
                        help_text="True if this reminder was auto-populated from manufacturer data",
                    ),
                ),
                (
                    "service_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reminders",
                        to="vehicle_maintenance_tracker.servicetype",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="vehicle_maintenance_tracker.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["next_due_date", "next_due_odometer"],
            },
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("content", models.TextField(help_text="Note content")),
                (
                    "odometer",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Optional odometer reading at time of note",
                        null=True,
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="URL to image in Garage S3 (optional)",
                        max_length=500,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="vehicle_maintenance_tracker.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ServiceRecordAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "file_url",
                    models.URLField(
                        help_text="URL to file in Garage S3", max_length=500
                    ),
                ),
                (
                    "file_name",
                    models.CharField(help_text="Original filename", max_length=255),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        default=0, help_text="File size in bytes"
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        default="application/octet-stream",
                        help_text="MIME type of the file",
                        max_length=100,
                    ),
                ),
                (
                    "service_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="vehicle_maintenance_tracker.servicerecord",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["service_record", "is_deleted"],
                        name="vehicle_mai_service_3c3282_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="servicetype",
            index=models.Index(
                fields=["is_custom", "is_deleted"],
                name="vehicle_mai_is_cust_c8f2f1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="servicetype",
            index=models.Index(
                fields=["user", "is_deleted"], name="vehicle_mai_user_id_f5d262_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="servicetype",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_custom", False), ("is_deleted", False)),
                fields=("name",),
                name="unique_system_service_type_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicetype",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_custom", True), ("is_deleted", False)),
                fields=("user", "name"),
                name="unique_user_service_type_name",
            ),
        ),
        migrations.AddIndex(
            model_name="shop",
            index=models.Index(
                fields=["owner", "is_deleted"], name="vehicle_mai_owner_i_c73085_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="shop",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("owner", "name"),
                name="unique_shop_name_per_user",
            ),
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(
                fields=["owner", "is_deleted", "is_archived"],
                name="vehicle_mai_owner_i_50f206_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(
                fields=["owner", "display_order"], name="vehicle_mai_owner_i_cf82e7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(fields=["vin"], name="vehicle_mai_vin_89a69f_idx"),
        ),
        migrations.AddIndex(
            model_name="servicerecord",
            index=models.Index(
                fields=["vehicle", "is_deleted", "-date"],
                name="vehicle_mai_vehicle_d39f69_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="servicerecord",
            index=models.Index(
                fields=["service_type", "is_deleted"],
                name="vehicle_mai_service_a8ffb5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="servicerecord",
            index=models.Index(fields=["date"], name="vehicle_mai_date_5eff31_idx"),
        ),
        migrations.AddIndex(
            model_name="reminder",
            index=models.Index(
                fields=["vehicle", "is_deleted"], name="vehicle_mai_vehicle_95c9be_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reminder",
            index=models.Index(
                fields=["next_due_date"], name="vehicle_mai_next_du_afa691_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="reminder",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("mileage_interval__isnull", False),
                    ("time_interval_months__isnull", False),
                    _connector="OR",
                ),
                name="reminder_has_interval",
            ),
        ),
        migrations.AddIndex(
            model_name="note",
            index=models.Index(
                fields=["vehicle", "is_deleted", "-created_at"],
                name="vehicle_mai_vehicle_cac0d4_idx",
            ),
        ),
    ]
