# Generated by Django 5.2.8 on 2025-12-01 00:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KanbanLane",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "name",
                    models.CharField(
                        help_text='Lane name (e.g., "In Progress", "Done")',
                        max_length=100,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#6B7280",
                        help_text="Hex color code for lane header",
                        max_length=7,
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, help_text='Default lane (usually "Backlog")'
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Order for displaying lanes left-to-right",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "color",
                    models.CharField(
                        default="#3B82F6",
                        help_text="Hex color code for project display",
                        max_length=7,
                    ),
                ),
                (
                    "item_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total number of items across all lists in this project",
                    ),
                ),
                (
                    "completed_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total number of completed items across all lists",
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Archived projects are hidden but not deleted",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Order for displaying projects (lower numbers first)",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TodoList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "view_mode",
                    models.CharField(
                        choices=[("list", "List View"), ("kanban", "Kanban View")],
                        default="list",
                        help_text="Current view mode for this list",
                        max_length=10,
                    ),
                ),
                (
                    "item_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Total number of items in this list"
                    ),
                ),
                (
                    "completed_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of completed items"
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Order within project or standalone lists",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="todo_lists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional: List can belong to a project",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lists",
                        to="todos.project",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TodoItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("completed", "Completed")],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when item was marked complete",
                        null=True,
                    ),
                ),
                (
                    "due_date",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Optional due date for time-sensitive tasks",
                        null=True,
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Order within list or kanban lane",
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Priority level (0=normal, higher=more important)",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "kanban_lane",
                    models.ForeignKey(
                        blank=True,
                        help_text="Lane assignment for kanban view (null for list view)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="todos.kanbanlane",
                    ),
                ),
                (
                    "todo_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="todos.todolist",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="kanbanlane",
            name="todo_list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="kanban_lanes",
                to="todos.todolist",
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["owner", "is_deleted", "is_archived"],
                name="todos_proje_owner_i_9220d3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["owner", "display_order"], name="todos_proje_owner_i_ad4e8a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.CheckConstraint(
                condition=models.Q(("item_count__gte", 0)),
                name="project_item_count_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.CheckConstraint(
                condition=models.Q(("completed_count__gte", 0)),
                name="project_completed_count_non_negative",
            ),
        ),
        migrations.AddIndex(
            model_name="todolist",
            index=models.Index(
                fields=["owner", "is_deleted"], name="todos_todol_owner_i_592be9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="todolist",
            index=models.Index(
                fields=["project", "is_deleted"], name="todos_todol_project_c7d885_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="todolist",
            index=models.Index(
                fields=["owner", "project", "display_order"],
                name="todos_todol_owner_i_4271f9_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="todolist",
            constraint=models.CheckConstraint(
                condition=models.Q(("item_count__gte", 0)),
                name="list_item_count_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="todolist",
            constraint=models.CheckConstraint(
                condition=models.Q(("completed_count__gte", 0)),
                name="list_completed_count_non_negative",
            ),
        ),
        migrations.AddIndex(
            model_name="todoitem",
            index=models.Index(
                fields=["todo_list", "is_deleted", "status"],
                name="todos_todoi_todo_li_8caa3a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="todoitem",
            index=models.Index(
                fields=["kanban_lane", "is_deleted", "display_order"],
                name="todos_todoi_kanban__e176ff_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="todoitem",
            index=models.Index(
                fields=["todo_list", "status", "display_order"],
                name="todos_todoi_todo_li_63fe9d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="todoitem",
            index=models.Index(
                fields=["completed_at"], name="todos_todoi_complet_bdef16_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="todoitem",
            index=models.Index(
                fields=["due_date"], name="todos_todoi_due_dat_6dbef3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="kanbanlane",
            index=models.Index(
                fields=["todo_list", "is_deleted", "display_order"],
                name="todos_kanba_todo_li_6b6450_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="kanbanlane",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("todo_list", "name"),
                name="unique_lane_name_per_list",
            ),
        ),
    ]
