# Generated by Django 5.2.8 on 2025-12-03 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todoitem",
            name="parent_item",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent item for subtasks (null for top-level items, max depth 2)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subtasks",
                to="todos.todoitem",
            ),
        ),
    ]
